// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	model "BookingService/src/model"

	mock "github.com/stretchr/testify/mock"

	user "BookingService/src/module/user"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Find provides a mock function with given fields: _a0
func (_m *Repository) Find(_a0 user.User) (model.User, error) {
	ret := _m.Called(_a0)

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(user.User) (model.User, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(user.User) model.User); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(user.User) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindViaEmailOrPhone provides a mock function with given fields: email, phone
func (_m *Repository) FindViaEmailOrPhone(email string, phone int) (model.User, error) {
	ret := _m.Called(email, phone)

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (model.User, error)); ok {
		return rf(email, phone)
	}
	if rf, ok := ret.Get(0).(func(string, int) model.User); ok {
		r0 = rf(email, phone)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(email, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
