// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	model "BookingService/src/model"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Find provides a mock function with given fields: id
func (_m *Repository) Find(id string) (model.SeatPricing, error) {
	ret := _m.Called(id)

	var r0 model.SeatPricing
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (model.SeatPricing, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) model.SeatPricing); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.SeatPricing)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
