// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	model "BookingService/src/model"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CheckBookingSeat provides a mock function with given fields: seats
func (_m *Repository) CheckBookingSeat(seats []model.SeatPrice) (bool, error) {
	ret := _m.Called(seats)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func([]model.SeatPrice) (bool, error)); ok {
		return rf(seats)
	}
	if rf, ok := ret.Get(0).(func([]model.SeatPrice) bool); ok {
		r0 = rf(seats)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func([]model.SeatPrice) error); ok {
		r1 = rf(seats)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Count provides a mock function with given fields: sclass
func (_m *Repository) Count(sclass string) (int, error) {
	ret := _m.Called(sclass)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(sclass)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(sclass)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sclass)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: booking, seats
func (_m *Repository) Create(booking model.Booking, seats []model.SeatPrice) (bool, error) {
	ret := _m.Called(booking, seats)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Booking, []model.SeatPrice) (bool, error)); ok {
		return rf(booking, seats)
	}
	if rf, ok := ret.Get(0).(func(model.Booking, []model.SeatPrice) bool); ok {
		r0 = rf(booking, seats)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(model.Booking, []model.SeatPrice) error); ok {
		r1 = rf(booking, seats)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields:
func (_m *Repository) FindAll() ([]model.SeatBooked, error) {
	ret := _m.Called()

	var r0 []model.SeatBooked
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.SeatBooked, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.SeatBooked); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SeatBooked)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByBookingId provides a mock function with given fields: booking
func (_m *Repository) FindAllByBookingId(booking model.Booking) ([]model.SeatBooked, error) {
	ret := _m.Called(booking)

	var r0 []model.SeatBooked
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Booking) ([]model.SeatBooked, error)); ok {
		return rf(booking)
	}
	if rf, ok := ret.Get(0).(func(model.Booking) []model.SeatBooked); ok {
		r0 = rf(booking)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SeatBooked)
		}
	}

	if rf, ok := ret.Get(1).(func(model.Booking) error); ok {
		r1 = rf(booking)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
